version: '3.8'

services:

  metrics-client:
    build:
      context: ./metrics-client
    volumes:
      - ./metrics-client:/app
    ports:
      - "3001:3000"
    links:
      - metrics-api

  metrics-api:
    build:
      context: ./metrics-api
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ./metrics-api:/app
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=metrics_app_development
      - DATABASE_HOST=db

  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metrics_app_development
      - TZ=Etc/UTC


volumes:
  postgres_data:
